name: 'Android Emulator Action combined with a cmd execution'
description: 'Starts Android emulator via existing Android SDK installation and executes a shell command in parallel'
author: 'Malinskiy'
inputs:
  api:
    description: 'api version of the emulator'
    default: '28'
  abi:
    description: 'abi of the emulator'
    default: 'x86'
  tag:
    description: 'default or google_apis'
    default: 'google_apis'
  cmd:
    description: 'cmd to execute while the emulator is running'
    default: ''
  verbose:
    description: 'be verbose'
    default: 'no'
runs:
  using: 'node12'
  main: 'lib/main.js'
